name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repositorio
      - uses: actions/checkout@v4

      # 2) Sustituye <<git SHA>> en tus decisiones
      - name: Update decision SHA
        run: |
          files=$(grep -rl '<<git SHA>>' decisiones/*.md || true)
          if [ -n "$files" ]; then
            for f in $files; do
              bash scripts/update_decision_sha.sh "$f" "$GITHUB_SHA"
            done
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add $files
            git commit -m "Update decision SHA [skip ci]" || echo "No changes to commit"
            git push origin main
          fi

      # 3) Instala Rust (estable)
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # 4) Instala Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 5) Instala wasm-pack
      - name: Install wasm-pack
        run: curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      # 6) Compila tu paquete WebAssembly
      - name: Build wasm package
        run: wasm-pack build --target web wasm_game

      # 7) Despliega en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

