name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repositorio
      - uses: actions/checkout@v4

      # 2) Instala Rust (estable)
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # 3) Instala Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 4) Instala wasm-pack
      - name: Install wasm-pack
        run: curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      # 5) Compila tu paquete WebAssembly
      - name: Build wasm package
        run: wasm-pack build --target web wasm_game

      # 6) Construye la documentación con MkDocs
      - name: Build MkDocs site
        run: |
          pip install -r requirements.txt
          mkdocs build

      # 7) Despliega en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

